spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
hapi:
  fhir:
    implementationguides:
      ips_1_0_0:
        url: http://web/package.tgz
        name: fhir.dhis2
        version: 0.1.0
    supported_resource_types:
      - Patient
      - Observation
      - Subscription
      - StructureDefinition
      - ValueSet
      - SearchParameter
      - NamingSystem
      - CodeSystem
      - ConceptMap
      - Binary
      - Questionnaire
      - QuestionnaireResponse
    subscription:
      resthook_enabled: true
